### PR TITLE
remove `new Function` calls

### PR DESCRIPTION
**Pull request by firien**
`new Function` may violate some sites Content Security Policy which can disable evals. All tests are passing, but I don't know if you want to replicate the conditional existence of these functions and throw errors. For instance throw an error if `relativeToGetter` is called and `@options.relativeTo` is not defined.

I'm also not sure what is allowed as `@type` for `VersionedStruct` - is it always a string representing a single property? or can it be a chain like `@options.relativeTo` on `Pointer`

### CODE REVIEW

**Comment by firien** [comment]
@devongovett did you get a chance to look at this?
The code coverage decrease is because these were conditional functions. These conditional functions may have been created (via new Function), but i think this reveals they were never executed afterwards.

**Comment by Brvtvs** [comment]
This change would be very helpful so that this library can be used with a secure CSP.

**Comment by jfoclpf** [comment]
Apologies cause I'm still a bit newbie on these github issues.

Considering that "this branch has no conflicts with the base branch", does it mean that the issue is already solved or immediately solvable? Thank you so much in advance

**Comment by firien** [comment]
"no conflicts" just means that the branch can be merged without a user having to manually fix conflicts. It does not guarantee integrity of the actual code - it could very well contain a syntax error…

It is the testing that matters, and that is passing; but the code coverage has some complaints…

@devongovett, would you have anytime to look into this?

**Comment by jfoclpf** [comment]
Thanks for the clarification.

**Comment by cbwebdevelopment** [comment]
@firien I'm running your fix in a local build of devongovett/pdfkit, and it has removed the unsafe-eval warnings, but Its taking many (guessing at least 10) times longer to generate the pdf.

Did you notice any significant performance degradation in your usage?

**Comment by firien** [comment]
I actually don't use it in production; I still use an older `pdfmake` that doesn't have evals.

But, I just wired it up and didn't notice any difference in speed. Although I am generating very small PDFs, both versions were taking ~300ms.

----

I can see how making an Array and reducing it may generate some overhead. @devongovett would know better than I if this function is cache-able.

**Comment by cbwebdevelopment** [comment]
Thanks for checking.  I believe it to be a problem with my local build process.

**Comment by jarrettj** [comment]
+1

**Comment by ArthurClemens** [comment]
[fontkit](https://github.com/foliojs/fontkit) tests fail with these changes

**Comment by firien** [comment]
From initial PR:
> I'm also not sure what is allowed as `@type` for `VersionedStruct` - is it always a string representing a single property? or can it be a chain like `@options.relativeTo` on `Pointer`

According to @ArthurClemens, the answer is: it can be a property chain.

There should probably be some local tests for this.

**Comment by firien** [comment]
updated for es6

**Comment by firien** [comment]
@devongovett, this PR has been updated for ES6, can you please review it? Any feedback would be appreciated.
Thank you.

**Comment by devongovett** [comment]
Closing in favor of #34. This is an API change though, so it'll be a major version bump.

**Pull request closed without merging**
